
import java.awt.Color;
import javax.swing.JOptionPane;
import java.io.*;
import java.sql.*;
import java.util.*;
/**
 *
 * @author 강재순
 */
public class MainFrame extends javax.swing.JFrame {

    String strDriver="com.microsoft.sqlserver.jdbc.SQLServerDriver";
    String strURL="jdbc:sqlserver://localhost:1433;DatabaseName=joinDB";
    String strUser="sa";
    String strPWD="dlsgkvmfwpr@_";
    static String sql=new String();
    Connection DB_con;
    Statement DB_stmt;
    ResultSet DB_rs;
    public static String id;
    
    public void setID(String id){ // 값 넘겨주기 위해서
        this.id=id;
    }
    public String getID(){
        return id;
    }
    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        getContentPane().setBackground(new Color(242,255,237)); // 프레임 배경 
    }
    public void dbOpen(){
        try{
            Class.forName(strDriver);
            DB_con=DriverManager.getConnection(strURL,strUser,strPWD);
            DB_stmt=DB_con.createStatement();
        }catch(Exception e){
            System.out.println("SQLException: "+e.getMessage());
        }
        
    }
    public void dbClose(){
        try{
            DB_con.close();
            DB_stmt.close();
        }catch(Exception e){
            System.out.println("SQLException: "+e.getMessage());
        }
    }
    
    static boolean idCheck = false;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtID1 = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        txtPhone = new javax.swing.JTextField();
        btnSign1 = new javax.swing.JButton();
        txtPwd1 = new javax.swing.JPasswordField();
        txtPwd2 = new javax.swing.JPasswordField();
        btnIDCheck = new javax.swing.JButton();
        jFrame2 = new javax.swing.JFrame();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        btnIDSearch = new javax.swing.JButton();
        btnPWSearch = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        txtSName = new javax.swing.JTextField();
        txtSPhone = new javax.swing.JTextField();
        txtSName1 = new javax.swing.JTextField();
        txtSID = new javax.swing.JTextField();
        txtSPhone1 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnLogin = new javax.swing.JButton();
        txtID = new javax.swing.JTextField();
        btnSign = new javax.swing.JButton();
        btnSearch = new javax.swing.JButton();
        txtPwd = new javax.swing.JPasswordField();
        btnExit = new javax.swing.JButton();

        jLabel4.setText("회원가입");

        jLabel5.setText("아이디");

        jLabel6.setText("비밀번호");

        jLabel7.setText("비밀번호 확인");

        jLabel8.setText("이 름");

        jLabel9.setText("핸드폰");

        txtID1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtID1KeyReleased(evt);
            }
        });

        btnSign1.setText("회원가입");
        btnSign1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSign1ActionPerformed(evt);
            }
        });

        btnIDCheck.setText("중복확인");
        btnIDCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIDCheckActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame1Layout.createSequentialGroup()
                .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnSign1)
                    .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jFrame1Layout.createSequentialGroup()
                            .addGap(163, 163, 163)
                            .addComponent(jLabel4))
                        .addGroup(jFrame1Layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel6)
                                .addComponent(jLabel7)
                                .addComponent(jLabel5)
                                .addComponent(jLabel8)
                                .addComponent(jLabel9))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
                                .addComponent(txtID1, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtPwd1, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtPwd2)
                                .addComponent(txtPhone))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnIDCheck))))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtID1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnIDCheck))
                .addGap(18, 18, 18)
                .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtPwd1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtPwd2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jFrame1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel8))
                    .addComponent(txtName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(btnSign1)
                .addGap(52, 52, 52))
        );

        jLabel10.setText("아이디 찾기");

        jLabel11.setText("핸드폰");

        jLabel13.setText("아이디");

        jLabel14.setText("이름");

        jLabel15.setText("핸드폰");

        btnIDSearch.setText("아이디 찾기");
        btnIDSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIDSearchActionPerformed(evt);
            }
        });

        btnPWSearch.setText("비밀번호 찾기");
        btnPWSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPWSearchActionPerformed(evt);
            }
        });

        jLabel16.setText("이름");

        jLabel17.setText("비밀번호 찾기");

        javax.swing.GroupLayout jFrame2Layout = new javax.swing.GroupLayout(jFrame2.getContentPane());
        jFrame2.getContentPane().setLayout(jFrame2Layout);
        jFrame2Layout.setHorizontalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame2Layout.createSequentialGroup()
                .addGap(145, 145, 145)
                .addComponent(jLabel17)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jFrame2Layout.createSequentialGroup()
                .addGroup(jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jFrame2Layout.createSequentialGroup()
                        .addContainerGap(71, Short.MAX_VALUE)
                        .addGroup(jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jFrame2Layout.createSequentialGroup()
                                .addGroup(jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel13))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtSName1)
                                    .addComponent(txtSID)
                                    .addComponent(txtSPhone1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jFrame2Layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addGroup(jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jFrame2Layout.createSequentialGroup()
                                            .addGroup(jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jLabel11)
                                                .addComponent(jLabel16))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(txtSName)
                                                .addComponent(txtSPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGap(91, 91, 91))
                                        .addComponent(btnIDSearch, javax.swing.GroupLayout.Alignment.TRAILING))
                                    .addGroup(jFrame2Layout.createSequentialGroup()
                                        .addGap(73, 73, 73)
                                        .addComponent(jLabel10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 149, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jFrame2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnPWSearch)))
                .addGap(33, 33, 33))
        );
        jFrame2Layout.setVerticalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame2Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addGroup(jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(txtSName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtSPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnIDSearch)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addComponent(jLabel17)
                .addGap(18, 18, 18)
                .addGroup(jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txtSName1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txtSID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(txtSPhone1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnPWSearch)
                .addGap(25, 25, 25))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("로그인");

        jLabel2.setText("아이디");

        jLabel3.setText("비밀번호");

        btnLogin.setText("로 그 인");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        btnSign.setText("회원가입");
        btnSign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignActionPerformed(evt);
            }
        });

        btnSearch.setText("아이디 / 비밀번호 찾기");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        btnExit.setText("프로그램종료(exit)");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btnSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnSign, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnLogin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel2)
                                .addComponent(jLabel3))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtPwd)
                                .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addComponent(jLabel1)))
                .addContainerGap(79, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabel1)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtPwd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnLogin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSign)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSearch)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnExit)
                .addContainerGap(76, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSignActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignActionPerformed
        jFrame1.setVisible(true);
        jFrame1.setSize(370,400);
        
        txtID1.setText(null);
        txtPwd1.setText(null);
        txtPwd2.setText(null);
        txtName.setText(null);
        txtPhone.setText(null);
    }//GEN-LAST:event_btnSignActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnSign1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSign1ActionPerformed
        if(txtID1.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "아이디를 입력해주세요");
            return;
        }else if(txtPwd1.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "비밀번호를 입력해주세요");
            return;
        }else if(txtPwd1.getText().length() < 4){
            JOptionPane.showMessageDialog(null, "비밀번호가 너무 짧습니다.");
            return;
        }else if(txtPwd2.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "비밀번호를 입력해주세요");
            return;
        }else if(txtName.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "이름을 입력해주세요");
            return;
        }else if(txtPhone.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "핸드폰 번호를 입력해주세요");
            return;
        }else if(txtPhone.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "숫자만 입력해주세요.");
            return;
        }else if(!txtPwd1.getText().equals(txtPwd2.getText())){
            JOptionPane.showMessageDialog(null, "비밀번호가 일치하지 않습니다.");
            return;
        }else if(!idCheck){
            JOptionPane.showMessageDialog(null, "중복확인을 해주세요");
            return;
        }
            
        
            sql="insert into join123 values (";
            sql+="'"+txtID1.getText()+"',";
            sql+="'"+txtPwd1.getText()+"',";
            sql+="'"+txtName.getText()+"',";
            sql+="'"+txtPhone.getText()+"')";
        try{
            dbOpen();
            DB_stmt.executeUpdate(sql);
            dbClose();
            JOptionPane.showMessageDialog(null, "회원가입 성공!");
            jFrame1.setVisible(false);
        }catch (Exception e){
            System.out.println("SQLException : " + e.getMessage());
        }
    }//GEN-LAST:event_btnSign1ActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        sql = "SELECT * from join123 where id='"+ txtID.getText() + "' and passwd ='"+txtPwd.getText()+"'";
	try {
            if(txtID.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "아이디를 입력해주세요");
                return;
            }else if(txtPwd.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "비밀번호를 입력해주세요");
                return;
            }
                
            dbOpen();
            DB_rs = DB_stmt.executeQuery(sql);
            while(DB_rs.next()){
                if(txtID.getText().equals(DB_rs.getString(1)) && txtPwd.getText().equals(DB_rs.getString(2))){
                    JOptionPane.showMessageDialog(null, "로그인 성공", "성공", JOptionPane.WARNING_MESSAGE);
                    id=txtID.getText();
                    //this.setID(DB_rs.getString(1));
                    calendar c=new calendar();
                    c.setVisible(true);
                    return;
                }
            }
            JOptionPane.showMessageDialog(null, "존재하지 않는 아이디거나 비밀번호가 다릅니다.", "경고", JOptionPane.WARNING_MESSAGE); 
            dbClose();
            return;
            }catch (Exception e) {
                System.out.println("SQLException : " + e.getMessage());
        }
              
    }//GEN-LAST:event_btnLoginActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        jFrame2.setVisible(true);
        jFrame2.setSize(400,520);
            
        txtSID.setText(null);
        txtSName.setText(null);
        txtSName1.setText(null);
        txtSPhone.setText(null);
        txtSPhone1.setText(null);
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnIDSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIDSearchActionPerformed
        sql = "SELECT * FROM join123 where name ='"+ txtSName.getText() + "' and phone ='" + txtSPhone.getText() + "'";
        try{
            if(txtSName.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "이름을 입력해주세요");
                return;
            }
            else if(txtSPhone.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "핸드폰 번호를 입력해주세요");
                return;
            }
            dbOpen();      
            DB_rs = DB_stmt.executeQuery(sql);
            while(DB_rs.next()){
                if(txtSName.getText().equals(DB_rs.getString(3)) && txtSPhone.getText().equals(DB_rs.getString(4))){
                    JOptionPane.showMessageDialog(null, txtSName.getText()+"님의 아이디는 " + DB_rs.getString(1)+ "입니다.", "성공", JOptionPane.WARNING_MESSAGE);
                    return;
                }
            }
            JOptionPane.showMessageDialog(null, "이름이나 핸드폰 번호가 일치하지 않습니다.", "경고", JOptionPane.WARNING_MESSAGE);
            dbClose();
            return;
            }catch (Exception e) {
                System.out.println("SQLException : " + e.getMessage());
        }                   
    }//GEN-LAST:event_btnIDSearchActionPerformed

    private void btnPWSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPWSearchActionPerformed
        
        sql = "SELECT * FROM join123 where name='" + txtSName1.getText() + "' and id ='" + txtSID.getText() + 
                "' and phone='" + txtSPhone1.getText() + "'";
        try{
            if(txtSName1.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "이름을 입력해주세요");
                return;
            }else if(txtSID.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "아이디를 입력해주세요");
                return;
            }else if(txtSPhone1.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "핸드폰 번호를 입력해주세요");
                return;
            }
            dbOpen();
            DB_rs = DB_stmt.executeQuery(sql);
            while(DB_rs.next()){
                if(txtSID.getText().equals(DB_rs.getString(1)) && txtSName1.getText().equals(DB_rs.getString(3)) 
                        && txtSPhone1.getText().equals(DB_rs.getString(4))){
                    JOptionPane.showMessageDialog(null, "비밀번호는 " + DB_rs.getString(2) + " 입니다.", "성공", JOptionPane.WARNING_MESSAGE);
                    return;
                }              
            }
            JOptionPane.showMessageDialog(null, "존재하지 않는 아이디거나 이름, 핸드폰번호가 다릅니다.", "경고", JOptionPane.WARNING_MESSAGE);           
            dbClose();
            return;
            } catch (Exception e) {
                System.out.println("SQLException : " + e.getMessage());
        }
    }//GEN-LAST:event_btnPWSearchActionPerformed

    private void btnIDCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIDCheckActionPerformed
        sql = "SELECT * FROM join123 where id='" + txtID1.getText() + "'";
        
        try{
            dbOpen();
            DB_rs = DB_stmt.executeQuery(sql);
            while(DB_rs.next()){
                
                if(txtID1.getText().equals(DB_rs.getString(1))){
                    JOptionPane.showMessageDialog(null, "중복된 아이디 입니다.", "경고", JOptionPane.WARNING_MESSAGE);
                    return;                               
                }   
            }           
            JOptionPane.showMessageDialog(null, "사용 가능한 아이디 입니다.", "메세지", JOptionPane.WARNING_MESSAGE);
            idCheck = true;
            dbClose();            
            return;             
        }catch(Exception e){
            System.out.println("SQLException : " + e.getMessage());
        }      
    }//GEN-LAST:event_btnIDCheckActionPerformed

    private void txtID1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtID1KeyReleased
        idCheck = false;
    }//GEN-LAST:event_txtID1KeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnIDCheck;
    private javax.swing.JButton btnIDSearch;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnPWSearch;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnSign;
    private javax.swing.JButton btnSign1;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JFrame jFrame2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    public javax.swing.JTextField txtID;
    private javax.swing.JTextField txtID1;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JPasswordField txtPwd;
    private javax.swing.JPasswordField txtPwd1;
    private javax.swing.JPasswordField txtPwd2;
    private javax.swing.JTextField txtSID;
    private javax.swing.JTextField txtSName;
    private javax.swing.JTextField txtSName1;
    private javax.swing.JTextField txtSPhone;
    private javax.swing.JTextField txtSPhone1;
    // End of variables declaration//GEN-END:variables
}
