
import java.awt.Color;
import java.awt.Font;
import java.awt.event.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Calendar;
import javax.swing.JOptionPane;
/**
 *
 * @author 강아연
 */
public class SecondFrame extends javax.swing.JFrame {
    calendar cals=new calendar();
    String strDriver="com.microsoft.sqlserver.jdbc.SQLServerDriver";
    String strURL="jdbc:sqlserver://localhost:1433;DatabaseName=CalendarMemo";
    String strUser="sa";
    String strPWD="dlsgkvmfwpr@_";
    String sql=new String();
    Connection DB_con;
    Statement DB_stmt;
    ResultSet DB_rs;
    int cnt=12; // 글자 크기 올리기 변수
    static String font=""; // 글씨체 저장하기
    static boolean bold=false;
    String id="";
    public int curYear,
            curMonth,
            curDays;
    
    public SecondFrame() {
        initComponents();
        id=new MainFrame().getID();
        getContentPane().setBackground(new Color(242,255,237)); // 프레임 배경 
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txtMemo = new javax.swing.JTextArea();
        btnDB = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        btnExit = new javax.swing.JMenuItem();
        menuAll = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        menuUp = new javax.swing.JMenuItem();
        menuDown = new javax.swing.JMenuItem();
        menuBold = new javax.swing.JMenuItem();
        menuFont1 = new javax.swing.JMenuItem();
        menuOri = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtMemo.setColumns(20);
        txtMemo.setRows(5);
        jScrollPane1.setViewportView(txtMemo);

        btnDB.setText("DB저장");
        btnDB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDBActionPerformed(evt);
            }
        });

        jMenu2.setText("설정");
        jMenu2.addMenuKeyListener(new javax.swing.event.MenuKeyListener() {
            public void menuKeyPressed(javax.swing.event.MenuKeyEvent evt) {
                jMenu2MenuKeyPressed(evt);
            }
            public void menuKeyReleased(javax.swing.event.MenuKeyEvent evt) {
            }
            public void menuKeyTyped(javax.swing.event.MenuKeyEvent evt) {
            }
        });
        jMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu2ActionPerformed(evt);
            }
        });

        btnExit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.ALT_MASK));
        btnExit.setText("종료");
        btnExit.addMenuKeyListener(new javax.swing.event.MenuKeyListener() {
            public void menuKeyPressed(javax.swing.event.MenuKeyEvent evt) {
                btnExitMenuKeyPressed(evt);
            }
            public void menuKeyReleased(javax.swing.event.MenuKeyEvent evt) {
            }
            public void menuKeyTyped(javax.swing.event.MenuKeyEvent evt) {
            }
        });
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        jMenu2.add(btnExit);

        menuAll.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_MASK));
        menuAll.setText("프로그램 자체 종료");
        menuAll.addMenuKeyListener(new javax.swing.event.MenuKeyListener() {
            public void menuKeyPressed(javax.swing.event.MenuKeyEvent evt) {
                menuAllMenuKeyPressed(evt);
            }
            public void menuKeyReleased(javax.swing.event.MenuKeyEvent evt) {
            }
            public void menuKeyTyped(javax.swing.event.MenuKeyEvent evt) {
            }
        });
        menuAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAllActionPerformed(evt);
            }
        });
        jMenu2.add(menuAll);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("글씨설정");

        menuUp.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.ALT_MASK));
        menuUp.setText("글씨 크게");
        menuUp.addMenuKeyListener(new javax.swing.event.MenuKeyListener() {
            public void menuKeyPressed(javax.swing.event.MenuKeyEvent evt) {
                menuUpMenuKeyPressed(evt);
            }
            public void menuKeyReleased(javax.swing.event.MenuKeyEvent evt) {
            }
            public void menuKeyTyped(javax.swing.event.MenuKeyEvent evt) {
            }
        });
        menuUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuUpActionPerformed(evt);
            }
        });
        jMenu3.add(menuUp);

        menuDown.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.ALT_MASK));
        menuDown.setText("글씨 작게");
        menuDown.addMenuKeyListener(new javax.swing.event.MenuKeyListener() {
            public void menuKeyPressed(javax.swing.event.MenuKeyEvent evt) {
                menuDownMenuKeyPressed(evt);
            }
            public void menuKeyReleased(javax.swing.event.MenuKeyEvent evt) {
            }
            public void menuKeyTyped(javax.swing.event.MenuKeyEvent evt) {
            }
        });
        menuDown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuDownActionPerformed(evt);
            }
        });
        jMenu3.add(menuDown);

        menuBold.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.ALT_MASK));
        menuBold.setText("글씨 굵게");
        menuBold.addMenuKeyListener(new javax.swing.event.MenuKeyListener() {
            public void menuKeyPressed(javax.swing.event.MenuKeyEvent evt) {
                menuBoldMenuKeyPressed(evt);
            }
            public void menuKeyReleased(javax.swing.event.MenuKeyEvent evt) {
            }
            public void menuKeyTyped(javax.swing.event.MenuKeyEvent evt) {
            }
        });
        menuBold.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuBoldActionPerformed(evt);
            }
        });
        jMenu3.add(menuBold);

        menuFont1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.ALT_MASK));
        menuFont1.setText("궁서체");
        menuFont1.addMenuKeyListener(new javax.swing.event.MenuKeyListener() {
            public void menuKeyPressed(javax.swing.event.MenuKeyEvent evt) {
                menuFont1MenuKeyPressed(evt);
            }
            public void menuKeyReleased(javax.swing.event.MenuKeyEvent evt) {
            }
            public void menuKeyTyped(javax.swing.event.MenuKeyEvent evt) {
            }
        });
        menuFont1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuFont1ActionPerformed(evt);
            }
        });
        jMenu3.add(menuFont1);

        menuOri.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.ALT_MASK));
        menuOri.setText("원래 글씨체로");
        menuOri.addMenuKeyListener(new javax.swing.event.MenuKeyListener() {
            public void menuKeyPressed(javax.swing.event.MenuKeyEvent evt) {
                menuOriMenuKeyPressed(evt);
            }
            public void menuKeyReleased(javax.swing.event.MenuKeyEvent evt) {
            }
            public void menuKeyTyped(javax.swing.event.MenuKeyEvent evt) {
            }
        });
        menuOri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuOriActionPerformed(evt);
            }
        });
        jMenu3.add(menuOri);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 421, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnDB)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnDB)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    public void dbOpen(){ // db 열기
        try{
            Class.forName(strDriver);
            DB_con=DriverManager.getConnection(strURL,strUser,strPWD);
            DB_stmt=DB_con.createStatement();
        }catch(Exception e){
            System.out.println("SQLException: "+e.getMessage());
        }
        
    }
    public void dbClose(){ // db 닫기
        try{
            DB_con.close();
            DB_stmt.close();
        }catch(Exception e){
            System.out.println("SQLException: "+e.getMessage());
        }
    }
    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        //this.dispose(); // 현재 창만 닫기
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnExitMenuKeyPressed(javax.swing.event.MenuKeyEvent evt) {//GEN-FIRST:event_btnExitMenuKeyPressed
        //this.dispose(); // 현재 창만 닫기
    }//GEN-LAST:event_btnExitMenuKeyPressed

    private void btnDBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDBActionPerformed
        // DB 저장 버튼
        MainFrame main=new MainFrame();
        String memotxt=txtMemo.getText(); 
            sql="insert into CALENDAR values (";
            sql+="'"+curYear+"',";
            sql+="'"+curMonth+"',";
            sql+="'"+curDays+"',";
            sql+="'"+memotxt+"',";
            sql+="'"+id+"');";
        try{
            dbOpen();
            System.out.println(sql);
            DB_stmt.executeUpdate(sql);
            dbClose();
            JOptionPane.showMessageDialog(null, "저장하였습니다.");           
            System.exit(0);
        }catch(Exception e){
                e.getMessage();
        }
    }//GEN-LAST:event_btnDBActionPerformed

    private void menuUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuUpActionPerformed
       // 글씨크기 키우는 메뉴
        ++cnt;
        if(font.equals("궁서체")){
            if(bold){
                txtMemo.setFont(new Font("궁서체",Font.BOLD,cnt));
            }else{
                txtMemo.setFont(new Font("궁서체",Font.PLAIN,cnt));
            }
        }else{
            if(bold){
                txtMemo.setFont(new Font("맑은고딕",Font.BOLD,cnt));
            }else{
                txtMemo.setFont(new Font("맑은고딕",Font.PLAIN,cnt));
            }
        }
    }//GEN-LAST:event_menuUpActionPerformed

    private void menuDownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuDownActionPerformed
        // 글씨크기 줄이는 메뉴
        --cnt;
        if(cnt==0){
            cnt=12;
        }
        if(font.equals("궁서체")){
            if(bold){
                txtMemo.setFont(new Font("궁서체",Font.BOLD,cnt));
            }else{
                txtMemo.setFont(new Font("궁서체",Font.PLAIN,cnt));
            }
        }else{
          if(bold){
                txtMemo.setFont(new Font("맑은고딕",Font.BOLD,cnt));
            }else{
              txtMemo.setFont(new Font("맑은고딕",Font.PLAIN,cnt));
          }
        }
    }//GEN-LAST:event_menuDownActionPerformed

    private void menuBoldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuBoldActionPerformed
        // 글씨체 두껍게 해주는 메뉴
        bold=txtMemo.getFont().isBold();
        if(font.equals("궁서체")){
            txtMemo.setFont(new Font("궁서체",Font.BOLD,cnt));
        }else{
            txtMemo.setFont(new Font("맑은고딕",Font.BOLD,cnt));
        }
    }//GEN-LAST:event_menuBoldActionPerformed

    private void menuUpMenuKeyPressed(javax.swing.event.MenuKeyEvent evt) {//GEN-FIRST:event_menuUpMenuKeyPressed
        // 글씨크기 키우는 메뉴
        ++cnt;
        if(font.equals("궁서체")){
            if(bold){
                txtMemo.setFont(new Font("궁서체",Font.BOLD,cnt));
            }else{
                txtMemo.setFont(new Font("궁서체",Font.PLAIN,cnt));
            }
        }else{
            if(bold){
                txtMemo.setFont(new Font("맑은고딕",Font.BOLD,cnt));
            }else{
                txtMemo.setFont(new Font("맑은고딕",Font.PLAIN,cnt));
            }
        }
    }//GEN-LAST:event_menuUpMenuKeyPressed

    private void menuDownMenuKeyPressed(javax.swing.event.MenuKeyEvent evt) {//GEN-FIRST:event_menuDownMenuKeyPressed
        // 글씨크기 줄이는 메뉴
        --cnt;
        if(cnt==0){
            cnt=12;
        }
        if(font.equals("궁서체")){
            if(bold){
                txtMemo.setFont(new Font("궁서체",Font.BOLD,cnt));
            }else{
                txtMemo.setFont(new Font("궁서체",Font.PLAIN,cnt));
            }
        }else{
          if(bold){
                txtMemo.setFont(new Font("맑은고딕",Font.BOLD,cnt));
            }else{
              txtMemo.setFont(new Font("맑은고딕",Font.PLAIN,cnt));
          }
        }
    }//GEN-LAST:event_menuDownMenuKeyPressed

    private void menuBoldMenuKeyPressed(javax.swing.event.MenuKeyEvent evt) {//GEN-FIRST:event_menuBoldMenuKeyPressed
        // 글씨체 두껍게 해주는 메뉴
        bold=txtMemo.getFont().isBold();
        if(font.equals("궁서체")){
            txtMemo.setFont(new Font("궁서체",Font.BOLD,cnt));
        }else{
            txtMemo.setFont(new Font("맑은고딕",Font.BOLD,cnt));
        }
    }//GEN-LAST:event_menuBoldMenuKeyPressed

    private void menuFont1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuFont1ActionPerformed
        // 궁서체로 바꿔주는 메뉴
        txtMemo.setFont(new Font("궁서체",Font.PLAIN,cnt));
        font=txtMemo.getFont().getFontName(); // 글씨체 변경 후 적용;
    }//GEN-LAST:event_menuFont1ActionPerformed

    private void menuFont1MenuKeyPressed(javax.swing.event.MenuKeyEvent evt) {//GEN-FIRST:event_menuFont1MenuKeyPressed
        // 궁서체로 바꿔주는 메뉴
        txtMemo.setFont(new Font("궁서체",Font.PLAIN,cnt));
        font=txtMemo.getFont().getFontName(); // 글씨체 변경 후 적용;
    }//GEN-LAST:event_menuFont1MenuKeyPressed

    private void menuOriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuOriActionPerformed
        // 맑은고딕으로(원래글씨체) 바꿔주는 메뉴
        txtMemo.setFont(new Font("맑은고딕",Font.PLAIN,cnt));
        font=txtMemo.getFont().getFontName(); // 글씨체 변경 후 적용
    }//GEN-LAST:event_menuOriActionPerformed

    private void jMenu2MenuKeyPressed(javax.swing.event.MenuKeyEvent evt) {//GEN-FIRST:event_jMenu2MenuKeyPressed
// 이건 잘못생긴거
    }//GEN-LAST:event_jMenu2MenuKeyPressed

    private void menuOriMenuKeyPressed(javax.swing.event.MenuKeyEvent evt) {//GEN-FIRST:event_menuOriMenuKeyPressed
        // 맑은고딕으로(원래글씨체) 바꿔주는 메뉴
        txtMemo.setFont(new Font("맑은고딕",Font.PLAIN,cnt));
        font=txtMemo.getFont().getFontName(); // 글씨체 변경 후 적용
    }//GEN-LAST:event_menuOriMenuKeyPressed

    private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed
        
    }//GEN-LAST:event_jMenu2ActionPerformed

    private void menuAllMenuKeyPressed(javax.swing.event.MenuKeyEvent evt) {//GEN-FIRST:event_menuAllMenuKeyPressed
        // 전체 다 종료시키기 메뉴
        System.exit(0);
    }//GEN-LAST:event_menuAllMenuKeyPressed

    private void menuAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAllActionPerformed
        System.exit(0); 
    }//GEN-LAST:event_menuAllActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SecondFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SecondFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SecondFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SecondFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SecondFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDB;
    private javax.swing.JMenuItem btnExit;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuItem menuAll;
    private javax.swing.JMenuItem menuBold;
    private javax.swing.JMenuItem menuDown;
    private javax.swing.JMenuItem menuFont1;
    private javax.swing.JMenuItem menuOri;
    private javax.swing.JMenuItem menuUp;
    public javax.swing.JTextArea txtMemo;
    // End of variables declaration//GEN-END:variables
}
